Mitovia/Controllers/MeasureScaleController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Mitovia.data;

namespace Mitovia.Controllers
{
    public class MeasureScaleController : Controller
    {
        private readonly MitoviaDbContext dbContext;
        public MeasureScaleController(MitoviaDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var measureScales = await dbContext.MeasureScale.ToListAsync();
            return View(measureScales);
        }
    }
}

Mitovia/Controllers/MeasuresController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Mitovia.data;
using Mitovia.Models;
using System.Linq;
using System.Threading.Tasks;

namespace Mitovia.Controllers
{
    public class MeasuresController : Controller
    {
        private readonly MitoviaDbContext dbContext;

        public MeasuresController(MitoviaDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        
        /*
         *          Get all Measures
         */
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var measuresWithDialNames = await dbContext.Measure
                .Select(m => new MeasureView
                {
                    ID = m.ID,
                    Name = m.Name,
                    DisplayName = m.DisplayName ?? m.Name,
                    Description = m.Description ?? "No Description Present",
                    LastUpdatedDate = m.LastUpdatedDate,
                    ValueDialID = m.ValueDialID,
                    // Include other properties as needed
                    ValueDialName = dbContext.ValueDial.Where(v => v.ID == m.ValueDialID).Select(v => v.Name).FirstOrDefault()
                })
                .ToListAsync();

            foreach (var measure in measuresWithDialNames)
            {
                measure.LastUpdatedDateString = measure.LastUpdatedDate.HasValue
                    ? measure.LastUpdatedDate.Value.ToString("dd MMM yyyy")
                    : string.Empty;
            }

            return View(measuresWithDialNames);
        }
        
        /*
         *  Get Add Measure Page 
         */
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        /*
         *  Add a NEW Measure 
         */
        [HttpPost]

        public async Task<IActionResult> Add(AddMeasure model)
        {
            /*
             *   Measure Name should be unique 
             */
            var existingMeasure = await dbContext.Measure.FirstOrDefaultAsync(x => x.Name == model.Name);
            if(existingMeasure != null)
            {
                ModelState.AddModelError("Name", "Measure with this name already exists");
                return RedirectToAction("Index");
            }
            var measure = new Measure
            {
                Name = model.Name,
                DisplayName = model.DisplayName ?? model.Name,
                Description = model.Description ?? "No Description Present",
                ValueDialID = model.ValueDialID
            };

            dbContext.Measure.Add(measure);
            await dbContext.SaveChangesAsync();

            return RedirectToAction("Add");   
        }
        
        /*
         *  View a Measure
         */
        [HttpGet]

        public async Task<IActionResult> View(int id)
        {
            var measure = await dbContext.Measure.FirstOrDefaultAsync(x => x.ID == id);
            
            var viewModel = new UpdateMeasure()
            {
                ID = measure.ID,
                Name = measure.Name,
                DisplayName = measure.DisplayName,
                Description = measure.Description,
                ValueDialID = measure.ValueDialID,
            };

            return View("View", viewModel);
        }
        
        /*
         *  Update a Measure 
         */
        [HttpPost]

        public async Task<IActionResult> Update(UpdateMeasure model)
        {
            var measure = await dbContext.Measure.FirstOrDefaultAsync(x => x.ID == model.ID);
            if (measure == null)
            {
                return RedirectToAction("Index");
            }
            measure.Name = model.Name;
            measure.DisplayName = model.DisplayName;
            measure.Description = model.Description;
            measure.ValueDialID = model.ValueDialID;

            // Save changes to the database
            await dbContext.SaveChangesAsync();

            return RedirectToAction("Index");
        }
        
        /*
         *  Delete a Measure
         */
        [HttpPost]

        public async Task<IActionResult> Delete(UpdateMeasure model)
        {
            var measure = await dbContext.Measure.FirstOrDefaultAsync(x => x.ID == model.ID);
            if (measure == null)
            {
                return RedirectToAction("Index");
            }
            dbContext.Measure.Remove(measure);
            await dbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }


    }
}

Mitovia/Controllers/ValueDialController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Mitovia.data;

namespace Mitovia.Controllers
{
    public class ValueDialController : Controller
    {
        private readonly MitoviaDbContext dbContext;
        public ValueDialController(MitoviaDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var valueDials = await dbContext.ValueDial.ToListAsync();
            return View(valueDials);
        }
    }
}

Mitovia/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mitovia</title>



    <!-- DevExtreme library -->

    <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <!-- DevExtreme theme -->
    <link rel="stylesheet" href="https://cdn3.devexpress.com/jslib/23.2.3/css/dx.light.css">

    <!-- DevExtreme libraries (reference only one of them) -->
    <script type="text/javascript" src="https://cdn3.devexpress.com/jslib/23.2.3/js/dx.all.js"></script>

    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>


</head>
<body class="dx-swatch-dark">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mitovia</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Measures" asp-action="Index">Measures</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MeasureScale" asp-action="Index">MeasureScale</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ValueDial" asp-action="Index">ValueDial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Measures" asp-action="Add">Add Measure</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Mitovia - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
 @await RenderSectionAsync("Scripts", required: false)
</body>
</html>